### ISSUE TITLE
FN not work

### ISSUE THREAD

**Issue by mosnster** [celerond256/X260-Opencore-Hackintosh#6]
help

**Comment by celerond256** [comment]
I already post the answer or Fn  issues, hope this helps.

**Comment by celerond256** [comment]
Update July 19, 2021

I got my Fn & Function keys worked with:

Add SSDT-KBRD.aml —> EFI > OC > ACPI
Add patch for above SSDT —> EFI > OC > config.plist > Root> ACPI > Patch (you must include all 18 patch. A copy paste from example to your config.plist will do, as long you paste it at the right place)
Install ONLY ThinkpadAssistant.dmg from Mzsturc. Don’t mix with YogaSMC, and also Karabiner-Elements.
SSDT-KBRD_patch.plist.zip
NB: Sometimes we’ll get our Command keys (win keys) swapped with Alt. IF, you install Karabiner-Elements, and or your config.plist > Kernel sorting order different from mine.
If resorting kernel in config.plist not your option, then just swap the keys via System Preferences > Keyboard > Modifier Keys.
[SSDT-KBRD_patch.plist.zip](https://github.com/celerond256/X260-Opencore-Hackintosh/files/6839618/SSDT-KBRD_patch.plist.zip)

**Comment by celerond256** [comment]
Fn will work if ThinkpadAssistant already running, so check the ThinkpadAssistant “Launch On Login” in the bar.
